import { Topic, TopicCategory, AudienceType } from "./types";

export const TIMER_PRESETS = [30, 60, 90, 120, 180, 300] as const;
export const DEFAULT_TIMER = 60;

export const AUDIENCE_LABELS: Record<AudienceType, string> = {
  child: "a 10-year-old child",
  teenager: "a teenager",
  "non-technical": "a non-technical adult",
  peer: "a peer with similar expertise",
  executive: "a business executive",
  interviewer: "a job interviewer",
};

export const TOPIC_CONCEPTS: Record<string, string[]> = {
  JavaScript: [
    "closures",
    "promises",
    "the event loop",
    "prototypal inheritance",
    "async/await",
    "hoisting",
    "higher-order functions",
    "the DOM",
    "arrow functions vs regular functions",
    "the this keyword",
    "destructuring",
    "spread and rest operators",
    "template literals",
    "modules (import/export)",
    "classes and inheritance",
    "callbacks",
    "promise chaining",
    "try/catch and error handling",
    "the fetch API",
    "map, filter, and reduce",
    "variable scoping (var, let, const)",
    "immediately invoked function expressions (IIFE)",
    "currying",
    "debouncing and throttling",
    "web workers",
    "service workers",
    "local storage vs session storage",
    "cookies",
    "regular expressions",
    "object vs Map",
    "array vs Set",
    "WeakMap and WeakSet",
    "symbols",
    "proxies and reflect",
    "generators and iterators",
    "garbage collection in JavaScript",
  ],
  Python: [
    "decorators",
    "generators",
    "list comprehensions",
    "the GIL",
    "duck typing",
    "context managers",
    "virtual environments",
    "dunder methods",
    "metaclasses",
    "iterators vs iterables",
    "the descriptor protocol",
    "multiple inheritance and MRO",
    "lambda functions",
    "map, filter, and reduce",
    "class methods vs static methods",
    "property decorators",
    "the *args and **kwargs syntax",
    "dictionary comprehensions",
    "set comprehensions",
    "the walrus operator",
    "asyncio and async/await",
    "the with statement",
    "exception handling and custom exceptions",
    "modules and packages",
    "the import system",
    "pip and package management",
    "type hints and annotations",
    "dataclasses",
    "named tuples",
    "function closures",
    "mutable vs immutable types",
    "shallow vs deep copy",
    "the is vs == operators",
    "pass by reference vs pass by value",
    "Python's memory management",
    "slots",
  ],
  "Machine Learning": [
    "gradient descent",
    "overfitting",
    "neural networks",
    "supervised vs unsupervised learning",
    "backpropagation",
    "bias-variance tradeoff",
    "decision trees",
    "cross-validation",
    "regularization (L1/L2)",
    "feature engineering",
    "ensemble methods (bagging vs boosting)",
    "precision vs recall",
    "ROC curves",
    "k-nearest neighbors",
    "dimensionality reduction (PCA)",
    "transfer learning",
  ],
  "Web Development": [
    "REST APIs",
    "CORS",
    "cookies vs sessions",
    "DNS resolution",
    "HTTPS/TLS",
    "caching strategies",
    "WebSockets",
    "responsive design",
    "the critical rendering path",
    "server-side rendering vs client-side rendering",
    "OAuth and authentication flows",
    "Content Security Policy",
    "progressive web apps",
    "service workers",
    "web accessibility (WCAG)",
    "GraphQL vs REST",
  ],
  Databases: [
    "SQL joins",
    "indexing (in databases)",
    "ACID properties",
    "normalization",
    "NoSQL vs SQL",
    "transactions (in databases)",
    "connection pooling",
    "sharding",
    "database replication",
    "CAP theorem",
    "query optimization",
    "stored procedures",
    "database migrations",
    "eventual consistency",
    "write-ahead logging",
    "materialized views",
  ],
  "Operating Systems": [
    "processes vs threads",
    "virtual memory (in OS)",
    "deadlocks",
    "file systems",
    "context switching",
    "scheduling algorithms (in OS)",
    "system calls",
    "page replacement (in OS)",
    "the heap (OS memory management)",
    "the stack (OS call stack)",
    "inter-process communication",
    "semaphores and mutexes",
    "memory-mapped I/O",
    "kernel space vs user space",
    "paging vs segmentation",
    "interrupts and interrupt handling",
  ],
  Networking: [
    "TCP vs UDP",
    "HTTP/2",
    "load balancing (in networking)",
    "CDNs",
    "the OSI model",
    "subnetting",
    "packet routing",
    "firewalls",
    "NAT (Network Address Translation)",
    "ARP (Address Resolution Protocol)",
    "BGP routing",
    "DHCP",
    "TCP three-way handshake",
    "HTTP status codes",
    "TLS handshake",
    "DNS records (A, CNAME, MX)",
  ],
  "Data Structures": [
    "hash tables",
    "binary search trees",
    "linked lists vs arrays",
    "graphs (in data structures)",
    "stacks and queues",
    "heaps (priority queue data structure)",
    "tries (prefix trees)",
    "B-trees",
    "red-black trees",
    "bloom filters",
    "skip lists",
    "adjacency list vs adjacency matrix",
    "disjoint set (union-find)",
    "circular buffers",
    "LRU cache implementation",
    "amortized time complexity",
  ],
  Physics: [
    "gravity",
    "quantum entanglement",
    "thermodynamics",
    "special relativity",
    "electromagnetic waves",
    "entropy (in physics)",
    "wave-particle duality",
    "Newton's laws",
    "conservation of energy",
    "Schrödinger's equation",
    "the photoelectric effect",
    "nuclear fission vs fusion",
    "the Doppler effect",
    "Ohm's law",
    "centripetal vs centrifugal force",
    "the Standard Model of particle physics",
  ],
  Economics: [
    "supply and demand",
    "inflation",
    "opportunity cost",
    "game theory",
    "monetary policy",
    "comparative advantage",
    "market equilibrium",
    "externalities",
    "GDP and how it's measured",
    "the Phillips curve",
    "moral hazard",
    "adverse selection",
    "fiscal policy vs monetary policy",
    "the tragedy of the commons",
    "price elasticity",
    "Keynesian vs classical economics",
  ],
};

export const PRESET_TOPICS: Topic[] = [
  { id: "javascript", name: "JavaScript", category: "technology" },
  { id: "python", name: "Python", category: "technology" },
  { id: "ml", name: "Machine Learning", category: "technology" },
  { id: "webdev", name: "Web Development", category: "technology" },
  { id: "databases", name: "Databases", category: "technology" },
  { id: "os", name: "Operating Systems", category: "technology" },
  { id: "networking", name: "Networking", category: "technology" },
  { id: "dsa", name: "Data Structures", category: "technology" },
  { id: "physics", name: "Physics", category: "science" },
  { id: "economics", name: "Economics", category: "humanities" },
];

export const MAX_PERSONA_LENGTH = 50;

export const CATEGORY_COLORS: Record<TopicCategory, string> = {
  technology: "bg-blue-100 text-blue-800 border-blue-200",
  science: "bg-purple-100 text-purple-800 border-purple-200",
  humanities: "bg-amber-100 text-amber-800 border-amber-200",
  business: "bg-green-100 text-green-800 border-green-200",
  lifestyle: "bg-pink-100 text-pink-800 border-pink-200",
  custom: "bg-gray-100 text-gray-800 border-gray-200",
};
